Source = \
	Companies.java \
	Company.java \
	Curve.java \
	Curves.java \
	ISO8601DateParser.java \
	LoggingMethod.java \
	LoggingMethods.java \
	Properties.java \
	Property.java \
	Pwls.java \
	PwlsWebService.java \
	Tool.java \
	ToolClass.java \
	ToolClasses.java \
	Tools.java \

Main = PwlsWebService

include $(DEV_HOME)/jpwls/Makefile
